#!/usr/bin/env bash
# Example: backend-neutral worktree cleanup.
# Generated by environments-manager. Add backend-specific cleanup from references.

set -euo pipefail

WORKTREE_PATH="${CODEX_WORKTREE_PATH:-${CURSOR_WORKTREE_PATH:-$(pwd)}}"
cd "$WORKTREE_PATH"

# Backend-specific cleanup goes here.
# Never guess resource names from branch names. Read them from env/config files
# or deterministic setup metadata created by worktree-up.sh.

rm -f .env .env.local .env.development.local
echo "removed local env files"
