#!/usr/bin/env bash
# Example: pnpm + Postgres project with all four setup steps enabled.
# Generated by environments-manager. Adapt the project section for your repo.

set -euo pipefail

WORKTREE_PATH="${CODEX_WORKTREE_PATH:-${CURSOR_WORKTREE_PATH:-$(pwd)}}"
SOURCE_PATH="${CODEX_SOURCE_TREE_PATH:-${ROOT_WORKTREE_PATH:-$HOME/Developer/saas/myapp}}"

cd "$WORKTREE_PATH"

# 1. Copy ignored env files
for f in .env .env.local .env.development.local; do
  if [[ -f "$SOURCE_PATH/$f" && ! -f "$WORKTREE_PATH/$f" ]]; then
    cp "$SOURCE_PATH/$f" "$WORKTREE_PATH/$f"
    echo "copied $f"
  fi
done

# 2. Install dependencies
if   [[ -f pnpm-lock.yaml ]]; then pnpm install
elif [[ -f bun.lock || -f bun.lockb ]]; then bun install
elif [[ -f yarn.lock ]]; then yarn install
elif [[ -f package-lock.json ]]; then npm install
fi

# 3. Worktree-isolated database
worktree_slug=$(basename "$WORKTREE_PATH" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
db_name="myapp_${worktree_slug}"

if [[ -f .env ]]; then
  if grep -qE '^DATABASE_URL=' .env; then
    if [[ "${MYAPP_RESET_DB:-0}" == "1" ]] && command -v dropdb >/dev/null 2>&1; then
      dropdb --if-exists -d postgres "$db_name" || true
    fi
    if command -v createdb >/dev/null 2>&1; then
      createdb -d postgres "$db_name" 2>/dev/null || true
    fi
    # Rewrite only the DB name in DATABASE_URL
    sed -i.bak -E "s|(DATABASE_URL=postgres://[^/]+)/[^?\"']+|\1/${db_name}|" .env && rm -f .env.bak
    echo "DB set to $db_name"
  fi
fi

# 4. Codegen
if [[ -f prisma/schema.prisma ]]; then
  pnpm prisma generate
fi

echo "worktree ready"
