#!/usr/bin/env bash
# Example: backend-neutral worktree setup.
# Generated by environments-manager. Add backend-specific blocks from references.

set -euo pipefail

WORKTREE_PATH="${CODEX_WORKTREE_PATH:-${CURSOR_WORKTREE_PATH:-$(pwd)}}"
SOURCE_PATH="${CODEX_SOURCE_TREE_PATH:-${ROOT_WORKTREE_PATH:-$HOME/Developer/saas/myapp}}"

cd "$WORKTREE_PATH"

# 1. Copy ignored env files
for f in .env .env.local .env.development.local; do
  if [[ -f "$SOURCE_PATH/$f" && ! -f "$WORKTREE_PATH/$f" ]]; then
    cp "$SOURCE_PATH/$f" "$WORKTREE_PATH/$f"
    echo "copied $f"
  fi
done

# 2. Install dependencies
if   [[ -f pnpm-lock.yaml ]]; then pnpm install
elif [[ -f bun.lock || -f bun.lockb ]]; then bun install
elif [[ -f yarn.lock ]]; then yarn install
elif [[ -f package-lock.json ]]; then npm install
fi

# 3. Backend isolation/seeding
# Load a backend reference before adding database-specific behavior:
# - references/postgresql.md
# - references/convex.md
# - researcher-agent findings for any other backend

# 4. Codegen (adapt to the project)
if [[ -f convex/convex.config.ts || -f convex/schema.ts ]]; then
  pnpm exec convex codegen
elif [[ -f prisma/schema.prisma ]]; then
  pnpm prisma generate
fi

echo "worktree ready"
